apiVersion: v1
kind: ConfigMap
metadata:
  name: csi-s3-config
  namespace: csi-s3
data:
  MINIO_ENDPOINT: "https://aistor.lan.cschuetze.de"
  MINIO_USETLS: "true"
  MINIO_REGION: "us-east-1"
  MINIO_BUCKET_PREFIX: "pvc-"
