apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: minio.s3.csi
  labels:
    app.kubernetes.io/part-of: minio-csi-s3
spec:
  attachRequired: false
  podInfoOnMount: false
  volumeLifecycleModes:
    - Persistent
  fsGroupPolicy: None