kind: Service
apiVersion: v1
metadata:
  name: s3-csi-provisioner
  namespace: kube-system
  labels:
    app: s3-csi-provisioner
spec:
  selector:
    app: s3-csi-provisioner
  ports:
    - name: csi-s3-dummy
      port: 65535
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: s3-csi-provisioner
  namespace: kube-system
spec:
  serviceName: "s3-csi-provisioner"
  replicas: 1
  selector:
    matchLabels:
      app: s3-csi-provisioner
  template:
    metadata:
      labels:
        app: s3-csi-provisioner
    spec:
      serviceAccount: csi-s3-provisioner-sa
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
      containers:
        # - name: csi-provisioner
        #   image: registry.k8s.io/sig-storage/csi-provisioner:v6.1.0
        #   args:
        #     - "--csi-address=$(ADDRESS)"
        #     - "--v=4"
        #   env:
        #     - name: ADDRESS
        #       value: /var/lib/kubelet/plugins/ru.yandex.s3.csi/csi.sock
        #   imagePullPolicy: "IfNotPresent"
        #   volumeMounts:
        #     - name: socket-dir
        #       mountPath: /var/lib/kubelet/plugins/ru.yandex.s3.csi
        - name: csi-s3
          image: cr.yandex/crp9ftr22d26age3hulg/csi-s3:0.43.3
          imagePullPolicy: IfNotPresent
          args:
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--nodeid=$(NODE_ID)"
            - "--v=4"
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/kubelet/plugins/ru.yandex.s3.csi/csi.sock
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/kubelet/plugins/ru.yandex.s3.csi
      volumes:
        - name: socket-dir
          emptyDir: {}
---
# This YAML file demonstrates how to deploy the external
# provisioner for use with the mock CSI driver. It
# depends on the RBAC definitions from rbac.yaml.
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: csi-provisioner
spec:
  replicas: 3
  selector:
    matchLabels:
      app: csi-provisioner
  template:
    metadata:
      labels:
        app: csi-provisioner
    spec:
      serviceAccount: csi-provisioner
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
      containers:
        # https://kubernetes-csi.github.io/docs/external-provisioner.html
        - name: csi-provisioner
          image: gcr.io/k8s-staging-sig-storage/csi-provisioner:v6.1.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--http-endpoint=:8080"
            - "--v=5" # log level
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/plugins/minio.s3.csi/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          ports:
            - containerPort: 8080
              name: http-endpoint
              protocol: TCP
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /healthz/leader-election
              port: http-endpoint
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 20
        
        - name: mock-driver
          image: quay.io/k8scsi/mock-driver:canary
          env:
            - name: CSI_ENDPOINT
              value: /var/lib/csi/sockets/pluginproxy/mock.socket
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
      volumes:
        - name: socket-dir
          emptyDir:
